/**
 * The validation gate for procedurally-generated questions.
 *
 * This — not which AI provider generates the content — is the actual fix
 * for the "missing passage" / "incomplete question" failure modes: nothing
 * generated by an LLM should ever reach a student without passing every one
 * of these checks first.
 */

export interface GeneratedQuestionCandidate {
  question_text?: string;
  passage?: string | null;
  choices?: { a?: string; b?: string; c?: string; d?: string } | Record<string, string>;
  correct_answer?: string;
  explanation?: string;
  hint?: string;
  topic?: string;
  section?: string;
  difficulty?: string;
}

const VALID_SECTIONS = ['math', 'reading', 'writing'];
const VALID_DIFFICULTIES = ['easy', 'medium', 'hard'];
const VALID_ANSWERS = ['a', 'b', 'c', 'd'];

export function validateGeneratedQuestion(q: GeneratedQuestionCandidate): string | null {
  if (!q.question_text || q.question_text.trim().length < 10) {
    return 'question_text missing or too short';
  }

  const choiceKeys = ['a', 'b', 'c', 'd'];
  if (!q.choices || choiceKeys.some((k) => !(q.choices as any)[k] || String((q.choices as any)[k]).trim().length === 0)) {
    return 'choices missing or incomplete — need non-empty a/b/c/d';
  }

  if (!q.correct_answer || !VALID_ANSWERS.includes(q.correct_answer)) {
    return 'correct_answer missing or not one of a/b/c/d';
  }

  if (!q.explanation || q.explanation.trim().length < 10) {
    return 'explanation missing or too short';
  }

  if (!q.topic || q.topic.trim().length === 0) {
    return 'topic missing';
  }

  if (!q.section || !VALID_SECTIONS.includes(q.section)) {
    return 'section missing or invalid';
  }

  if (!q.difficulty || !VALID_DIFFICULTIES.includes(q.difficulty)) {
    return 'difficulty missing or invalid';
  }

  // The one check directly targeting the historical "passage went missing"
  // bug: if a passage is present at all, it has to actually be a passage,
  // not a token gesture at one.
  if (q.passage && q.passage.trim().length > 0 && q.passage.trim().length < 100) {
    return 'passage present but too short to be a real passage';
  }

  // Reading-section questions should have a real passage. Not a hard reject
  // (some reading questions are vocab-in-context without a full passage),
  // but worth flagging distinctly if it's suspiciously short or absent.
  if (q.section === 'reading' && (!q.passage || q.passage.trim().length < 100)) {
    return 'reading question missing a substantial passage';
  }

  return null; // null = valid
}

export interface ValidatedQuestion {
  question_text: string;
  passage: string | null;
  choices: { a: string; b: string; c: string; d: string };
  correct_answer: 'a' | 'b' | 'c' | 'd';
  explanation: string;
  hint: string | null;
  topic: string;
  section: 'math' | 'reading' | 'writing';
  difficulty: 'easy' | 'medium' | 'hard';
}

/** Filters a batch of AI-generated candidates down to only the ones that pass validation. */
export function filterValidQuestions(candidates: GeneratedQuestionCandidate[]): {
  valid: ValidatedQuestion[];
  rejected: { candidate: GeneratedQuestionCandidate; reason: string }[];
} {
  const valid: ValidatedQuestion[] = [];
  const rejected: { candidate: GeneratedQuestionCandidate; reason: string }[] = [];

  for (const candidate of candidates) {
    const reason = validateGeneratedQuestion(candidate);
    if (reason) {
      rejected.push({ candidate, reason });
    } else {
      valid.push({
        question_text: candidate.question_text!.trim(),
        passage: candidate.passage?.trim() || null,
        choices: {
          a: String((candidate.choices as any).a),
          b: String((candidate.choices as any).b),
          c: String((candidate.choices as any).c),
          d: String((candidate.choices as any).d),
        },
        correct_answer: candidate.correct_answer as 'a' | 'b' | 'c' | 'd',
        explanation: candidate.explanation!.trim(),
        hint: candidate.hint?.trim() || null,
        topic: candidate.topic!.trim(),
        section: candidate.section as 'math' | 'reading' | 'writing',
        difficulty: candidate.difficulty as 'easy' | 'medium' | 'hard',
      });
    }
  }

  return { valid, rejected };
}
