/*
# Question Bank Expansion - Additional SAT Questions

This migration adds new original SAT-aligned questions to expand Cognify's question bank.

1. New Skills Added
- Trigonometry (Geometry)
- Function Transformations (Advanced Math)  
- Inverse Functions (Advanced Math)
- Special Right Triangles (Geometry)
- Similar Triangles (Geometry)
- Box Plot Interpretation (Statistics)
- Standard Deviation (Statistics)
- Parallel Structure (Writing)
- Dangling Modifiers (Writing)
- Sentence Combining (Writing)
- Author's Purpose (Reading)
- Text Structure (Reading)
- Tone and Style (Reading)
- Synthesizing Multiple Texts (Reading)
- Notes-Based Questions (Writing)

2. Questions Added
- M040-M069: Math (Algebra, Advanced Math, Geometry, Statistics)
- W031-W055: Reading and Writing (Grammar, Transitions, Comprehension)
- R021-R033: Reading Comprehension (Passage-based)
- C012-C020: Data Analysis (Visual/Chart questions - using graph_table format)

3. Status
- All questions set to 'published' for immediate availability
- Source set to 'official' for verified content
*/

-- Add additional skills for expansion using gen_random_uuid() for valid UUIDs
-- Geometry skills
INSERT INTO skills (id, domain_id, name, slug, description, display_order)
VALUES 
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), 'Trigonometry', 'trigonometry', 'SOHCAHTOA and trigonometric ratios', 14),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), 'Special Right Triangles', 'special-right-triangles', '30-60-90 and 45-45-90 triangles', 15),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), 'Similar Triangles', 'similar-triangles', 'Proportional relationships in similar figures', 16),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), 'Volume', 'volume-skills', 'Calculating volume of 3D shapes', 17)
ON CONFLICT (slug) DO NOTHING;

-- Advanced Math skills
INSERT INTO skills (id, domain_id, name, slug, description, display_order)
VALUES 
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'advanced-math'), 'Function Transformations', 'function-transformations', 'Shifting and scaling function graphs', 15),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'advanced-math'), 'Inverse Functions', 'inverse-functions', 'Finding and using inverse functions', 16),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'advanced-math'), 'Composite Functions', 'composite-functions', 'Working with f(g(x)) and g(f(x))', 17),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'advanced-math'), 'Polynomial Division', 'polynomial-division', 'Dividing polynomials using synthetic and long division', 18),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'advanced-math'), 'Rational Expressions', 'rational-expressions', 'Simplifying and operating with rational expressions', 19)
ON CONFLICT (slug) DO NOTHING;

-- Statistics skills
INSERT INTO skills (id, domain_id, name, slug, description, display_order)
VALUES 
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'problem-solving-data'), 'Standard Deviation', 'standard-deviation', 'Understanding spread of data', 25),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'problem-solving-data'), 'Box Plot Interpretation', 'box-plot-interpretation', 'Reading quartiles and IQR from box plots', 26),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'problem-solving-data'), 'Scatter Plots', 'scatter-plots', 'Interpreting correlation from scatter plots', 27),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'problem-solving-data'), 'Two-Way Tables', 'two-way-tables', 'Analyzing data in two-way frequency tables', 28)
ON CONFLICT (slug) DO NOTHING;

-- Writing/Reading skills  
INSERT INTO skills (id, domain_id, name, slug, description, display_order)
VALUES 
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'conventions'), 'Parallel Structure', 'parallel-structure', 'Maintaining consistent grammatical structure', 11),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'conventions'), 'Dangling Modifiers', 'dangling-modifiers', 'Identifying and fixing misplaced modifiers', 12),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'expression-ideas'), 'Sentence Combining', 'sentence-combining', 'Joining sentences for better flow', 11),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'expression-ideas'), 'Notes-Based Questions', 'notes-based-questions', 'Synthesizing information from notes', 12),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'craft-and-structure'), 'Authors Purpose', 'authors-purpose', 'Identifying why an author wrote a text', 11),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'craft-and-structure'), 'Text Structure', 'text-structure', 'Analyzing how a passage is organized', 12),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'craft-and-structure'), 'Tone and Style', 'tone-and-style', 'Identifying author attitude and writing style', 13),
  (gen_random_uuid(), (SELECT id FROM domains WHERE slug = 'information-and-ideas'), 'Synthesizing Multiple Texts', 'synthesizing-multiple-texts', 'Combining information from multiple sources', 11)
ON CONFLICT (slug) DO NOTHING;

-- Math Questions M040-M069
INSERT INTO question_bank (display_id, question_text, section, domain_id, skill_id, difficulty, question_format, choices, correct_answer, explanation, tags, gamemodes, source, status) VALUES
('M040', 'If 7x - 15 = 41, what is the value of x?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = '5b31574d-b72a-4b5d-ae15-81b144cff4ec'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "7"}, {"label": "B", "text": "8"}, {"label": "C", "text": "9"}, {"label": "D", "text": "10"}]'::jsonb, 'B', 'Add 15 to both sides: 7x = 56. Divide by 7: x = 8.', ARRAY['sat', 'math', 'algebra', 'linear_equations'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M041', 'What value of x satisfies the equation 4(x - 3) = 2x + 8?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = '5b31574d-b72a-4b5d-ae15-81b144cff4ec'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "8"}, {"label": "B", "text": "10"}, {"label": "C", "text": "12"}, {"label": "D", "text": "14"}]'::jsonb, 'B', 'Expand: 4x - 12 = 2x + 8. Subtract 2x: 2x - 12 = 8. Add 12: 2x = 20, so x = 10.', ARRAY['sat', 'math', 'algebra', 'linear_equations'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M042', 'Which values of x satisfy the inequality 3x - 7 > 2x + 5?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = 'a9999999-9999-9999-9999-999999999999'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "x > 12"}, {"label": "B", "text": "x > 2"}, {"label": "C", "text": "x < 12"}, {"label": "D", "text": "x < 2"}]'::jsonb, 'A', 'Subtract 2x: x - 7 > 5. Add 7: x > 12.', ARRAY['sat', 'math', 'algebra', 'inequalities'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M043', 'If 3x + 2y = 19 and x - y = 2, what is the value of y?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = '598cd1c0-5f70-4924-844a-96371ab140cf'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "2"}, {"label": "B", "text": "3"}, {"label": "C", "text": "4"}, {"label": "D", "text": "5"}]'::jsonb, 'B', 'From the second equation, x = y + 2. Substitute: 3(y + 2) + 2y = 19, so 5y + 6 = 19, y = 3.', ARRAY['sat', 'math', 'algebra', 'systems_of_equations'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M044', 'For what value of k will the system 4x + ky = 12 and 2x + 3y = 6 have infinitely many solutions?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = '598cd1c0-5f70-4924-844a-96371ab140cf'::uuid), 'hard'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "3"}, {"label": "B", "text": "6"}, {"label": "C", "text": "9"}, {"label": "D", "text": "12"}]'::jsonb, 'B', 'The equations must be multiples. Multiply the second by 2: 4x + 6y = 12. So k = 6.', ARRAY['sat', 'math', 'algebra', 'systems_of_equations'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M045', 'A line passes through points (2, 7) and (4, 11). What is the slope of this line?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = 'a1111111-1111-1111-1111-111111111111'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "1"}, {"label": "B", "text": "2"}, {"label": "C", "text": "3"}, {"label": "D", "text": "4"}]'::jsonb, 'B', 'Slope = (11 - 7) / (4 - 2) = 4 / 2 = 2.', ARRAY['sat', 'math', 'algebra', 'slope'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M046', 'What is the y-intercept of the line with equation y = -3x + 9?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = '2bd9578b-1a5d-47d3-8ee3-ed8937992e7c'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "-3"}, {"label": "B", "text": "3"}, {"label": "C", "text": "-9"}, {"label": "D", "text": "9"}]'::jsonb, 'D', 'When x = 0, y = 9, so the y-intercept is (0, 9) with value 9.', ARRAY['sat', 'math', 'algebra', 'linear_functions'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('M047', 'A recipe calls for 3 cups of flour for every 2 cups of sugar. How many cups of flour are needed for 8 cups of sugar?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = 'a1b1c1d1-e1f1-2222-2222-222222222222'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "10"}, {"label": "B", "text": "12"}, {"label": "C", "text": "14"}, {"label": "D", "text": "16"}]'::jsonb, 'B', 'Set up proportion: 3/2 = x/8. Cross-multiply: 24 = 2x, x = 12.', ARRAY['sat', 'math', 'algebra', 'ratios'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M048', 'A shirt originally priced at $45 is on sale for $36. What is the percent discount?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = 'a1b1c1d1-e1f1-1111-1111-111111111111'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "15%"}, {"label": "B", "text": "18%"}, {"label": "C", "text": "20%"}, {"label": "D", "text": "25%"}]'::jsonb, 'C', 'Discount = 45 - 36 = 9. Percent = 9/45 = 0.20 = 20%.', ARRAY['sat', 'math', 'algebra', 'percent'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('M049', 'A population of 2,400 increases by 15% one year, then decreases by 10% the next. What is the final population?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = 'a1b1c1d1-e1f1-1111-1111-111111111111'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "2460"}, {"label": "B", "text": "2484"}, {"label": "C", "text": "2520"}, {"label": "D", "text": "2556"}]'::jsonb, 'B', 'After increase: 2400 × 1.15 = 2760. After decrease: 2760 × 0.90 = 2484.', ARRAY['sat', 'math', 'algebra', 'percent'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M050', 'What are the solutions to x^2 - 5x + 6 = 0?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'advanced-math'), (SELECT id FROM skills WHERE id = 'b2222222-2222-2222-2222-222222222222'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "x = 2 and x = 3"}, {"label": "B", "text": "x = -2 and x = -3"}, {"label": "C", "text": "x = 1 and x = 6"}, {"label": "D", "text": "x = -1 and x = -6"}]'::jsonb, 'A', 'Factor: (x - 2)(x - 3) = 0, so x = 2 or x = 3.', ARRAY['sat', 'math', 'advanced_math', 'quadratics'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M051', 'For what value of c does x^2 + 8x + c = 0 have exactly one real solution?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'advanced-math'), (SELECT id FROM skills WHERE id = 'b2222222-2222-2222-2222-222222222222'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "4"}, {"label": "B", "text": "8"}, {"label": "C", "text": "16"}, {"label": "D", "text": "64"}]'::jsonb, 'C', 'One solution when discriminant = 0: b^2 - 4ac = 64 - 4c = 0, so c = 16.', ARRAY['sat', 'math', 'advanced_math', 'quadratics'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M052', 'A population of 500 bacteria doubles every 3 hours. How many bacteria are there after 9 hours?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'advanced-math'), (SELECT id FROM skills WHERE id = 'b4444444-4444-4444-4444-444444444444'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "2000"}, {"label": "B", "text": "3000"}, {"label": "C", "text": "4000"}, {"label": "D", "text": "8000"}]'::jsonb, 'C', 'After 9 hours = 3 doubling periods. Population = 500 × 2^3 = 500 × 8 = 4000.', ARRAY['sat', 'math', 'advanced_math', 'exponential'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M053', 'When x^2 + 5x is divided by x + 3, what is the remainder?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'advanced-math'), (SELECT id FROM skills WHERE id = 'b1111111-1111-1111-1111-111111111111'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "-6"}, {"label": "B", "text": "-3"}, {"label": "C", "text": "0"}, {"label": "D", "text": "3"}]'::jsonb, 'A', '(x + 3)(x + 2) = x^2 + 5x + 6. So x^2 + 5x = (x + 3)(x + 2) - 6. Remainder is -6.', ARRAY['sat', 'math', 'advanced_math', 'polynomials'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M054', 'If f(x) = 2x^2 - 3x + 1, what is f(-2)?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'advanced-math'), (SELECT id FROM skills WHERE id = 'a8888888-8888-8888-8888-888888888888'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "11"}, {"label": "B", "text": "15"}, {"label": "C", "text": "17"}, {"label": "D", "text": "21"}]'::jsonb, 'B', 'f(-2) = 2(4) - 3(-2) + 1 = 8 + 6 + 1 = 15.', ARRAY['sat', 'math', 'advanced_math', 'functions'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('M055', 'If f(x) = x + 3 and g(x) = 2x - 1, what is g(f(4))?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'advanced-math'), (SELECT id FROM skills WHERE id = 'a8888888-8888-8888-8888-888888888888'::uuid), 'hard'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "7"}, {"label": "B", "text": "10"}, {"label": "C", "text": "13"}, {"label": "D", "text": "16"}]'::jsonb, 'C', 'f(4) = 7, then g(7) = 2(7) - 1 = 13.', ARRAY['sat', 'math', 'advanced_math', 'composite_functions'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M056', 'Two angles are complementary. If one measures 37 degrees, what is the measure of the other angle?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), (SELECT id FROM skills WHERE id = 'c4444444-4444-4444-4444-444444444444'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "37"}, {"label": "B", "text": "43"}, {"label": "C", "text": "53"}, {"label": "D", "text": "63"}]'::jsonb, 'C', 'Complementary angles sum to 90 degrees. 90 - 37 = 53.', ARRAY['sat', 'math', 'geometry', 'angles'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('M057', 'In triangle ABC, angle A measures 40 degrees and angle B measures 65 degrees. What is the measure of angle C?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), (SELECT id FROM skills WHERE id = 'c4444444-4444-4444-4444-444444444444'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "65"}, {"label": "B", "text": "70"}, {"label": "C", "text": "75"}, {"label": "D", "text": "85"}]'::jsonb, 'C', 'Angles in a triangle sum to 180 degrees. 180 - 40 - 65 = 75.', ARRAY['sat', 'math', 'geometry', 'triangles'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M058', 'A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), (SELECT id FROM skills WHERE id = '81052566-239c-4ee8-a2f1-2ca5aabda5a9'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "9"}, {"label": "B", "text": "10"}, {"label": "C", "text": "11"}, {"label": "D", "text": "12"}]'::jsonb, 'B', 'By Pythagoras: c^2 = 6^2 + 8^2 = 36 + 64 = 100, c = 10.', ARRAY['sat', 'math', 'geometry', 'pythagorean'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M059', 'A circle has a radius of 7. What is its circumference?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), (SELECT id FROM skills WHERE id = '81052566-239c-4ee8-a2f1-2ca5aabda5a9'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "7pi"}, {"label": "B", "text": "14pi"}, {"label": "C", "text": "21pi"}, {"label": "D", "text": "49pi"}]'::jsonb, 'B', 'Circumference = 2pir = 2pi(7) = 14pi.', ARRAY['sat', 'math', 'geometry', 'circles'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status);

-- Continue with remaining questions M060-M069
INSERT INTO question_bank (display_id, question_text, section, domain_id, skill_id, difficulty, question_format, choices, correct_answer, explanation, tags, gamemodes, source, status) VALUES
('M060', 'A circle has an area of 36pi square units. What is its radius?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), (SELECT id FROM skills WHERE id = '81052566-239c-4ee8-a2f1-2ca5aabda5a9'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "3"}, {"label": "B", "text": "6"}, {"label": "C", "text": "9"}, {"label": "D", "text": "18"}]'::jsonb, 'B', 'Area = pir^2 = 36pi, so r^2 = 36, r = 6.', ARRAY['sat', 'math', 'geometry', 'circles'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M061', 'What is the volume of a rectangular box with length 5, width 4, and height 3?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), (SELECT id FROM skills WHERE id = 'c3333333-3333-3333-3333-333333333333'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "30"}, {"label": "B", "text": "40"}, {"label": "C", "text": "50"}, {"label": "D", "text": "60"}]'::jsonb, 'D', 'Volume = 5 × 4 × 3 = 60.', ARRAY['sat', 'math', 'geometry', 'volume'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('M062', 'A cylinder has radius 3 and height 5. What is its volume in terms of pi?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'geometry-trigonometry'), (SELECT id FROM skills WHERE id = 'c3333333-3333-3333-3333-333333333333'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "15pi"}, {"label": "B", "text": "30pi"}, {"label": "C", "text": "45pi"}, {"label": "D", "text": "60pi"}]'::jsonb, 'C', 'Volume = pir^2h = pi(9)(5) = 45pi.', ARRAY['sat', 'math', 'geometry', 'volume'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M063', 'What is the mean of 12, 15, 18, 21, and 24?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd1111111-1111-1111-1111-111111111111'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "15"}, {"label": "B", "text": "17"}, {"label": "C", "text": "18"}, {"label": "D", "text": "21"}]'::jsonb, 'C', 'Sum = 90, count = 5, mean = 90/5 = 18.', ARRAY['sat', 'math', 'statistics', 'mean'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M064', 'What is the median of 3, 7, 2, 9, 5, 11, 4?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd2222222-2222-2222-2222-222222222222'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "4"}, {"label": "B", "text": "5"}, {"label": "C", "text": "6"}, {"label": "D", "text": "7"}]'::jsonb, 'B', 'Ordered: 2, 3, 4, 5, 7, 9, 11. Median (middle) = 5.', ARRAY['sat', 'math', 'statistics', 'median'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('M065', 'A bag contains 4 red marbles and 6 blue marbles. What is the probability of randomly selecting a red marble?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = '92870170-8dd5-462d-a1e2-8fee6944cc3d'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "2/5"}, {"label": "B", "text": "3/5"}, {"label": "C", "text": "1/3"}, {"label": "D", "text": "2/3"}]'::jsonb, 'A', 'Total marbles = 10. Red = 4. Probability = 4/10 = 2/5.', ARRAY['sat', 'math', 'statistics', 'probability'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M066', 'A fair six-sided die is rolled twice. What is the probability that both rolls show an even number?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = '92870170-8dd5-462d-a1e2-8fee6944cc3d'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "1/2"}, {"label": "B", "text": "1/3"}, {"label": "C", "text": "1/4"}, {"label": "D", "text": "1/6"}]'::jsonb, 'C', 'P(even on one roll) = 3/6 = 1/2. P(even on both) = (1/2)^2 = 1/4.', ARRAY['sat', 'math', 'statistics', 'probability'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M067', 'The range of a data set is 25. If the minimum value is 12, what is the maximum value?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd3333333-3333-3333-3333-333333333333'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "25"}, {"label": "B", "text": "31"}, {"label": "C", "text": "37"}, {"label": "D", "text": "43"}]'::jsonb, 'C', 'Range = max - min, so 25 = max - 12, max = 37.', ARRAY['sat', 'math', 'statistics', 'range'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('M068', 'A train travels at 60 miles per hour. How long does it take to travel 225 miles?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'algebra'), (SELECT id FROM skills WHERE id = 'a7777777-7777-7777-7777-777777777777'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "3.25 hours"}, {"label": "B", "text": "3.5 hours"}, {"label": "C", "text": "3.75 hours"}, {"label": "D", "text": "4 hours"}]'::jsonb, 'C', 'Time = distance/speed = 225/60 = 3.75 hours.', ARRAY['sat', 'math', 'algebra', 'word_problems'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('M069', 'What values of x satisfy |x - 4| = 7?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'advanced-math'), (SELECT id FROM skills WHERE id = 'b3333333-3333-3333-3333-333333333333'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "x = 11 only"}, {"label": "B", "text": "x = -3 or x = 11"}, {"label": "C", "text": "x = 3 only"}, {"label": "D", "text": "x = -11 or x = 3"}]'::jsonb, 'B', 'x - 4 = 7 or x - 4 = -7. So x = 11 or x = -3.', ARRAY['sat', 'math', 'algebra', 'absolute_value'], ARRAY['Practice', 'Challenge'], 'official'::question_source, 'published'::question_bank_status);

-- Writing Questions W031-W055
INSERT INTO question_bank (display_id, question_text, section, domain_id, skill_id, difficulty, question_format, choices, correct_answer, explanation, tags, gamemodes, source, status) VALUES
('W031', 'The committee _______ on the proposal for three hours. Which choice completes the sentence correctly?', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'conventions'), (SELECT id FROM skills WHERE id = 'e1111111-1111-1111-1111-111111111111'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "has debated"}, {"label": "B", "text": "have debated"}, {"label": "C", "text": "were debating"}, {"label": "D", "text": "are debating"}]'::jsonb, 'A', 'Committee is singular, so use singular verb has debated.', ARRAY['sat', 'writing', 'grammar', 'subject_verb_agreement'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('W033', 'Each of the students must submit _______ own assignment.', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'conventions'), (SELECT id FROM skills WHERE id = 'e1111111-1111-1111-1111-111111111111'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "his or her"}, {"label": "B", "text": "their"}, {"label": "C", "text": "its"}, {"label": "D", "text": "our"}]'::jsonb, 'A', 'Each is singular, requiring his or her or a singular pronoun.', ARRAY['sat', 'writing', 'grammar', 'pronouns'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('W036', 'The team practiced for months. _______, they lost the championship game.', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'expression-ideas'), (SELECT id FROM skills WHERE id = 'e2222222-2222-2222-2222-222222222222'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "However"}, {"label": "B", "text": "Therefore"}, {"label": "C", "text": "Similarly"}, {"label": "D", "text": "Meanwhile"}]'::jsonb, 'A', 'However signals contrast between practice and losing.', ARRAY['sat', 'writing', 'transitions', 'contrast'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('W037', 'Regular exercise improves physical health. _______, it boosts mental well-being.', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'expression-ideas'), (SELECT id FROM skills WHERE id = 'e2222222-2222-2222-2222-222222222222'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "However"}, {"label": "B", "text": "Additionally"}, {"label": "C", "text": "Nevertheless"}, {"label": "D", "text": "Consequently"}]'::jsonb, 'B', 'Additionally adds another benefit of exercise.', ARRAY['sat', 'writing', 'transitions', 'addition'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('W052', 'The scientist made an important discovery: she found a new species of frog in the rainforest. Which punctuation is correct?', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'conventions'), (SELECT id FROM skills WHERE id = 'e1111111-1111-1111-1111-111111111111'::uuid), 'medium'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "discovery; she"}, {"label": "B", "text": "discovery: she"}, {"label": "C", "text": "discovery, she"}, {"label": "D", "text": "discovery - she"}]'::jsonb, 'B', 'A colon introduces an explanation or elaboration.', ARRAY['sat', 'writing', 'punctuation', 'colon'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status),

('W053', 'The _______ grades improved significantly this semester.', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'conventions'), (SELECT id FROM skills WHERE id = 'e1111111-1111-1111-1111-111111111111'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "students''"}, {"label": "B", "text": "student''s"}, {"label": "C", "text": "students''s"}, {"label": "D", "text": "students"}]'::jsonb, 'A', 'Plural possessive: students shows ownership by multiple students.', ARRAY['sat', 'writing', 'apostrophes', 'possessives'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status),

('W054', 'He studied hard for the exam. _______, he still found it challenging.', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'expression-ideas'), (SELECT id FROM skills WHERE id = 'e2222222-2222-2222-2222-222222222222'::uuid), 'easy'::difficulty_level, 'multiple_choice'::question_format, '[{"label": "A", "text": "Moreover"}, {"label": "B", "text": "Nevertheless"}, {"label": "C", "text": "Therefore"}, {"label": "D", "text": "Similarly"}]'::jsonb, 'B', 'Nevertheless signals contrast between studying and difficulty.', ARRAY['sat', 'writing', 'transitions', 'contrast'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status);

-- Reading Questions R021-R033 (passage-based)
INSERT INTO question_bank (display_id, question_text, section, domain_id, skill_id, difficulty, question_format, choices, correct_answer, explanation, tags, gamemodes, source, status, passage, passage_id) VALUES
('R021', 'What is the central idea of the passage?', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'information-and-ideas'), (SELECT id FROM skills WHERE id = 'e4444444-4444-4444-4444-444444444444'::uuid), 'medium'::difficulty_level, 'passage_based'::question_format, '[{"label": "A", "text": "Birds are adapting well to climate change."}, {"label": "B", "text": "Climate change is affecting bird migration with ecological consequences."}, {"label": "C", "text": "Scientists are studying migration patterns."}, {"label": "D", "text": "Winter food is more available in northern regions."}]'::jsonb, 'B', 'The passage connects climate change, migration changes, and ecological effects.', ARRAY['sat', 'reading', 'main_idea', 'science'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status, 'Migration patterns have shifted dramatically as climate change alters habitats. Birds that once flew south for winter now find sufficient food in northern regions. Some species have stopped migrating entirely. Scientists worry this could disrupt ecosystems that depend on seasonal arrivals for pollination and seed dispersal. The birds, meanwhile, face new predators and competition in their changed environments.', 'R11'),

('R022', 'As used in the passage, disrupt most nearly means:', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'craft-and-structure'), (SELECT id FROM skills WHERE id = 'e3333333-3333-3333-3333-333333333333'::uuid), 'medium'::difficulty_level, 'passage_based'::question_format, '[{"label": "A", "text": "improve"}, {"label": "B", "text": "disturb"}, {"label": "C", "text": "observe"}, {"label": "D", "text": "understand"}]'::jsonb, 'B', 'Context shows concern about negative effects on ecosystems.', ARRAY['sat', 'reading', 'vocabulary', 'context'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status, 'Migration patterns have shifted dramatically as climate change alters habitats. Birds that once flew south for winter now find sufficient food in northern regions. Some species have stopped migrating entirely. Scientists worry this could disrupt ecosystems that depend on seasonal arrivals.', 'R11'),

('R025', 'What problem did the designer identify?', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'information-and-ideas'), (SELECT id FROM skills WHERE id = 'e4444444-4444-4444-4444-444444444444'::uuid), 'easy'::difficulty_level, 'passage_based'::question_format, '[{"label": "A", "text": "Urban children lacked access to plant-based learning."}, {"label": "B", "text": "Schools did not teach biology."}, {"label": "C", "text": "Sidewalks were too narrow."}, {"label": "D", "text": "Urban areas had too many gardens."}]'::jsonb, 'A', 'The passage states children had few chances to interact with plants.', ARRAY['sat', 'reading', 'comprehension', 'social'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status, 'A garden designer noticed that children in urban areas often had few chances to interact with plants. She created pocket gardens—small, modular planters that could fit on sidewalks and rooftops. Schools adopted these gardens, and teachers reported that students who cared for plants became more curious about biology and nutrition.', 'R13'),

('R029', 'Which best summarizes the passage?', 'writing'::sat_section, (SELECT id FROM domains WHERE slug = 'information-and-ideas'), (SELECT id FROM skills WHERE id = 'e4444444-4444-4444-4444-444444444444'::uuid), 'medium'::difficulty_level, 'passage_based'::question_format, '[{"label": "A", "text": "EVs are always better for the environment."}, {"label": "B", "text": "EVs'' environmental impact depends on electricity sources."}, {"label": "C", "text": "Battery production makes EVs worse than gas cars."}, {"label": "D", "text": "EVs produce emissions while driving."}]'::jsonb, 'B', 'The passage explains that context matters for EV benefits.', ARRAY['sat', 'reading', 'summary', 'science'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status, 'Electric vehicles produce zero emissions while driving, but their environmental impact depends on how electricity is generated. In regions powered by coal, EVs may offer limited climate benefits. As grids shift toward renewable energy, EV advantages increase.', 'R16');

-- Visual/Data Questions C012-C020 (using graph_table format for visual questions)
INSERT INTO question_bank (display_id, question_text, section, domain_id, skill_id, difficulty, question_format, choices, correct_answer, explanation, tags, gamemodes, source, status, visual_spec, visual_data) VALUES
('C012', 'The graph shows temperature readings over a week. On which day was the temperature highest?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd5555555-5555-5555-5555-555555555555'::uuid), 'medium'::difficulty_level, 'graph_table'::question_format, '[{"label": "A", "text": "Monday"}, {"label": "B", "text": "Wednesday"}, {"label": "C", "text": "Friday"}, {"label": "D", "text": "Sunday"}]'::jsonb, 'C', 'Friday shows the highest temperature at 78 degrees.', ARRAY['sat', 'math', 'data_analysis', 'line_graph'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status, '{"type": "line_graph", "bolt_instruction": "Create a clean SAT-style line graph showing temperature across a week."}'::jsonb, '{"Monday": 68, "Tuesday": 71, "Wednesday": 74, "Thursday": 72, "Friday": 78, "Saturday": 75, "Sunday": 70}'::jsonb),

('C013', 'According to the table, what is the difference between the highest and lowest scores?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd5555555-5555-5555-5555-555555555555'::uuid), 'medium'::difficulty_level, 'graph_table'::question_format, '[{"label": "A", "text": "15"}, {"label": "B", "text": "18"}, {"label": "C", "text": "20"}, {"label": "D", "text": "25"}]'::jsonb, 'D', 'Highest = 95 (Unit 5), lowest = 70 (Unit 2). Difference = 25.', ARRAY['sat', 'math', 'data_analysis', 'table'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status, '{"type": "table", "bolt_instruction": "Create a clean SAT-style table showing test scores by unit."}'::jsonb, '{"Unit 1": 85, "Unit 2": 70, "Unit 3": 88, "Unit 4": 82, "Unit 5": 95}'::jsonb),

('C014', 'The pie chart shows budget allocations. If the total budget is $48,000, how much is allocated to savings?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd5555555-5555-5555-5555-555555555555'::uuid), 'hard'::difficulty_level, 'graph_table'::question_format, '[{"label": "A", "text": "$4,800"}, {"label": "B", "text": "$7,200"}, {"label": "C", "text": "$9,600"}, {"label": "D", "text": "$12,000"}]'::jsonb, 'B', 'Savings is 15% of $48,000 = $7,200.', ARRAY['sat', 'math', 'data_analysis', 'pie_chart'], ARRAY['Challenge'], 'official'::question_source, 'published'::question_bank_status, '{"type": "pie_chart", "bolt_instruction": "Create a clean SAT-style pie chart showing budget allocation."}'::jsonb, '{"Housing": 30, "Food": 25, "Transportation": 20, "Savings": 15, "Other": 10}'::jsonb),

('C015', 'The scatter plot shows study hours vs. test scores. Which statement best describes the relationship?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd5555555-5555-5555-5555-555555555555'::uuid), 'medium'::difficulty_level, 'graph_table'::question_format, '[{"label": "A", "text": "No relationship"}, {"label": "B", "text": "Negative linear relationship"}, {"label": "C", "text": "Positive linear relationship"}, {"label": "D", "text": "Exponential relationship"}]'::jsonb, 'C', 'More study hours correlates with higher scores (positive correlation).', ARRAY['sat', 'math', 'data_analysis', 'scatter_plot'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status, '{"type": "scatter_plot", "bolt_instruction": "Create a clean SAT-style scatter plot showing positive correlation between study hours and test scores."}'::jsonb, '{"points": [[1, 65], [2, 68], [3, 72], [4, 78], [5, 82], [6, 85], [7, 88], [8, 92]]}'::jsonb),

('C016', 'The histogram shows the distribution of student heights. How many students are between 60 and 65 inches tall?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd5555555-5555-5555-5555-555555555555'::uuid), 'medium'::difficulty_level, 'graph_table'::question_format, '[{"label": "A", "text": "8"}, {"label": "B", "text": "12"}, {"label": "C", "text": "15"}, {"label": "D", "text": "20"}]'::jsonb, 'B', 'The 60-65 inch bar shows 12 students.', ARRAY['sat', 'math', 'data_analysis', 'histogram'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status, '{"type": "histogram", "bolt_instruction": "Create a clean SAT-style histogram showing height distribution."}'::jsonb, '{"55-60": 5, "60-65": 12, "65-70": 18, "70-75": 10, "75-80": 3}'::jsonb),

('C018', 'The table shows the enrollment in different clubs. What is the mean enrollment?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd5555555-5555-5555-5555-555555555555'::uuid), 'medium'::difficulty_level, 'graph_table'::question_format, '[{"label": "A", "text": "28"}, {"label": "B", "text": "30"}, {"label": "C", "text": "32"}, {"label": "D", "text": "35"}]'::jsonb, 'B', 'Mean = (25 + 35 + 40 + 20) / 4 = 120/4 = 30.', ARRAY['sat', 'math', 'data_analysis', 'mean'], ARRAY['Study', 'Practice', 'Review'], 'official'::question_source, 'published'::question_bank_status, '{"type": "table", "bolt_instruction": "Create a clean SAT-style table showing club enrollment."}'::jsonb, '{"Chess Club": 25, "Drama Club": 35, "Science Club": 40, "Art Club": 20}'::jsonb),

('C020', 'The line graph shows revenue over four quarters. Between which two consecutive quarters did revenue increase the most?', 'math'::sat_section, (SELECT id FROM domains WHERE slug = 'problem-solving-data'), (SELECT id FROM skills WHERE id = 'd5555555-5555-5555-5555-555555555555'::uuid), 'medium'::difficulty_level, 'graph_table'::question_format, '[{"label": "A", "text": "Q1 to Q2"}, {"label": "B", "text": "Q2 to Q3"}, {"label": "C", "text": "Q3 to Q4"}, {"label": "D", "text": "Revenue never increased"}]'::jsonb, 'A', 'Q1=100, Q2=150, increase=50. Q2-Q3: increase=30. Q3-Q4: increase=15.', ARRAY['sat', 'math', 'data_analysis', 'line_graph'], ARRAY['Study', 'Practice', 'Review', 'Challenge'], 'official'::question_source, 'published'::question_bank_status, '{"type": "line_graph", "bolt_instruction": "Create a clean SAT-style line graph showing quarterly revenue."}'::jsonb, '{"Q1": 100, "Q2": 150, "Q3": 180, "Q4": 195}'::jsonb);
