import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      approved_team_emails: {
        Row: {
          id: string;
          email: string;
          intended_role: 'student' | 'creator' | 'admin';
          invited_by: string | null;
          invited_at: string;
          notes: string | null;
          is_used: boolean;
          used_at: string | null;
          used_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          intended_role?: 'student' | 'creator' | 'admin';
          invited_by?: string | null;
          invited_at?: string;
          notes?: string | null;
          is_used?: boolean;
          used_at?: string | null;
          used_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          intended_role?: 'student' | 'creator' | 'admin';
          invited_by?: string | null;
          invited_at?: string;
          notes?: string | null;
          is_used?: boolean;
          used_at?: string | null;
          used_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      role_requests: {
        Row: {
          id: string;
          user_id: string;
          existing_role: 'student' | 'creator' | 'admin';
          requested_role: 'student' | 'creator' | 'admin';
          status: 'pending' | 'approved' | 'rejected' | 'cancelled';
          reason: string | null;
          admin_notes: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          existing_role: 'student' | 'creator' | 'admin';
          requested_role: 'student' | 'creator' | 'admin';
          status?: 'pending' | 'approved' | 'rejected' | 'cancelled';
          reason?: string | null;
          admin_notes?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          existing_role?: 'student' | 'creator' | 'admin';
          requested_role?: 'student' | 'creator' | 'admin';
          status?: 'pending' | 'approved' | 'rejected' | 'cancelled';
          reason?: string | null;
          admin_notes?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          actor_id: string;
          action: 'role_changed' | 'role_request_approved' | 'role_request_rejected' | 'team_email_added' | 'team_email_removed' | 'user_suspended' | 'user_unsuspended' | 'question_claimed' | 'question_released' | 'response_approved' | 'response_rejected';
          target_user_id: string | null;
          target_entity_type: string | null;
          target_entity_id: string | null;
          old_value: Json;
          new_value: Json;
          metadata: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string;
          action: 'role_changed' | 'role_request_approved' | 'role_request_rejected' | 'team_email_added' | 'team_email_removed' | 'user_suspended' | 'user_unsuspended' | 'question_claimed' | 'question_released' | 'response_approved' | 'response_rejected';
          target_user_id?: string | null;
          target_entity_type?: string | null;
          target_entity_id?: string | null;
          old_value?: Json;
          new_value?: Json;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string;
          action?: 'role_changed' | 'role_request_approved' | 'role_request_rejected' | 'team_email_added' | 'team_email_removed' | 'user_suspended' | 'user_unsuspended' | 'question_claimed' | 'question_released' | 'response_approved' | 'response_rejected';
          target_user_id?: string | null;
          target_entity_type?: string | null;
          target_entity_id?: string | null;
          old_value?: Json;
          new_value?: Json;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: 'student' | 'creator' | 'admin';
          grade_level: number | null;
          target_sat_score: number | null;
          test_date: string | null;
          preferred_subjects: string[];
          bio: string | null;
          specialties: string[];
          is_verified: boolean;
          onboarding_completed: boolean;
          onboarding_step: number;
          preferences: Json;
          role_approved_at: string | null;
          role_approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: 'student' | 'creator' | 'admin';
          grade_level?: number | null;
          target_sat_score?: number | null;
          test_date?: string | null;
          preferred_subjects?: string[];
          bio?: string | null;
          specialties?: string[];
          is_verified?: boolean;
          onboarding_completed?: boolean;
          onboarding_step?: number;
          preferences?: Json;
          role_approved_at?: string | null;
          role_approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: 'student' | 'creator' | 'admin';
          grade_level?: number | null;
          target_sat_score?: number | null;
          test_date?: string | null;
          preferred_subjects?: string[];
          bio?: string | null;
          specialties?: string[];
          is_verified?: boolean;
          onboarding_completed?: boolean;
          onboarding_step?: number;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      questions: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          content: string;
          question_type: string;
          subject_id: string | null;
          domain_id: string | null;
          topic_id: string | null;
          status: 'draft' | 'pending' | 'processing' | 'ai_ready' | 'human_requested' | 'claimed' | 'human_ready' | 'completed' | 'archived';
          student_notes: string | null;
          difficulty_perceived: string | null;
          ocr_extracted_text: string | null;
          ocr_confidence: number | null;
          human_requested: boolean;
          human_request_notes: string | null;
          metadata: Json;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          title?: string | null;
          content: string;
          question_type?: string;
          subject_id?: string | null;
          domain_id?: string | null;
          topic_id?: string | null;
          status?: 'draft' | 'pending' | 'processing' | 'ai_ready' | 'human_requested' | 'claimed' | 'human_ready' | 'completed' | 'archived';
          student_notes?: string | null;
          difficulty_perceived?: string | null;
          ocr_extracted_text?: string | null;
          ocr_confidence?: number | null;
          human_requested?: boolean;
          human_request_notes?: string | null;
          metadata?: Json;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string | null;
          content?: string;
          question_type?: string;
          subject_id?: string | null;
          domain_id?: string | null;
          topic_id?: string | null;
          status?: 'draft' | 'pending' | 'processing' | 'ai_ready' | 'human_requested' | 'claimed' | 'human_ready' | 'completed' | 'archived';
          student_notes?: string | null;
          difficulty_perceived?: string | null;
          ocr_extracted_text?: string | null;
          ocr_confidence?: number | null;
          human_requested?: boolean;
          human_request_notes?: string | null;
          metadata?: Json;
          deleted_at?: string | null;
          updated_at?: string;
          completed_at?: string | null;
        };
      };
      procedural_questions: {
        Row: {
          id: string;
          question_text: string;
          passage: string | null;
          choices: Json;
          correct_answer: string;
          explanation: string;
          hint: string | null;
          topic: string;
          section: 'math' | 'reading' | 'writing';
          difficulty: 'easy' | 'medium' | 'hard';
          provider: string;
          times_served: number;
          promoted_to_bank_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          question_text: string;
          passage?: string | null;
          choices: Json;
          correct_answer: string;
          explanation: string;
          hint?: string | null;
          topic: string;
          section: 'math' | 'reading' | 'writing';
          difficulty: 'easy' | 'medium' | 'hard';
          provider: string;
          times_served?: number;
          promoted_to_bank_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          question_text?: string;
          passage?: string | null;
          choices?: Json;
          correct_answer?: string;
          explanation?: string;
          hint?: string | null;
          topic?: string;
          section?: 'math' | 'reading' | 'writing';
          difficulty?: 'easy' | 'medium' | 'hard';
          provider?: string;
          times_served?: number;
          promoted_to_bank_id?: string | null;
          created_at?: string;
        };
      };
      subjects: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          display_order?: number;
        };
      };
      domains: {
        Row: {
          id: string;
          subject_id: string;
          name: string;
          slug: string;
          description: string | null;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          subject_id: string;
          name: string;
          slug: string;
          description?: string | null;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          subject_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          display_order?: number;
        };
      };
      ai_responses: {
        Row: {
          id: string;
          question_id: string;
          explanation: string;
          hints: string[] | null;
          detected_subject_id: string | null;
          detected_domain_id: string | null;
          detected_topic_id: string | null;
          confidence_score: number | null;
          follow_up_questions: Json;
          related_concepts: string[] | null;
          status: 'pending' | 'processing' | 'ready' | 'failed';
          provider: string | null;
          model_version: string | null;
          tokens_used: number | null;
          student_rating: number | null;
          student_feedback: string | null;
          processing_time_ms: number | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          question_id: string;
          explanation: string;
          hints?: string[] | null;
          detected_subject_id?: string | null;
          detected_domain_id?: string | null;
          detected_topic_id?: string | null;
          confidence_score?: number | null;
          follow_up_questions?: Json;
          related_concepts?: string[] | null;
          status?: 'pending' | 'processing' | 'ready' | 'failed';
          provider?: string | null;
          model_version?: string | null;
          tokens_used?: number | null;
          student_rating?: number | null;
          student_feedback?: string | null;
          processing_time_ms?: number | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          explanation?: string;
          hints?: string[] | null;
          detected_subject_id?: string | null;
          detected_domain_id?: string | null;
          detected_topic_id?: string | null;
          confidence_score?: number | null;
          follow_up_questions?: Json;
          related_concepts?: string[] | null;
          status?: 'pending' | 'processing' | 'ready' | 'failed';
          provider?: string | null;
          model_version?: string | null;
          tokens_used?: number | null;
          student_rating?: number | null;
          student_feedback?: string | null;
          processing_time_ms?: number | null;
          metadata?: Json;
          updated_at?: string;
        };
      };
      human_responses: {
        Row: {
          id: string;
          question_id: string;
          claim_id: string;
          creator_id: string;
          explanation: string;
          teaching_notes: string | null;
          video_url: string | null;
          video_storage_path: string | null;
          video_storage_bucket: string | null;
          video_duration_seconds: number | null;
          annotated_images: Json;
          status: 'pending' | 'processing' | 'ready' | 'failed';
          is_approved: boolean;
          student_rating: number | null;
          student_feedback: string | null;
          admin_rating: number | null;
          admin_feedback: string | null;
          rejection_reason: string | null;
          metadata: Json;
          promoted_to_bank: boolean;
          bank_question_id: string | null;
          created_at: string;
          updated_at: string;
          approved_at: string | null;
        };
        Insert: {
          id?: string;
          question_id: string;
          claim_id: string;
          creator_id: string;
          explanation: string;
          teaching_notes?: string | null;
          video_url?: string | null;
          video_storage_path?: string | null;
          video_storage_bucket?: string | null;
          video_duration_seconds?: number | null;
          annotated_images?: Json;
          status?: 'pending' | 'processing' | 'ready' | 'failed';
          is_approved?: boolean;
          student_rating?: number | null;
          student_feedback?: string | null;
          admin_rating?: number | null;
          admin_feedback?: string | null;
          rejection_reason?: string | null;
          metadata?: Json;
          promoted_to_bank?: boolean;
          bank_question_id?: string | null;
          created_at?: string;
          updated_at?: string;
          approved_at?: string | null;
        };
        Update: {
          id?: string;
          explanation?: string;
          teaching_notes?: string | null;
          video_url?: string | null;
          video_storage_path?: string | null;
          video_storage_bucket?: string | null;
          video_duration_seconds?: number | null;
          annotated_images?: Json;
          status?: 'pending' | 'processing' | 'ready' | 'failed';
          is_approved?: boolean;
          student_rating?: number | null;
          student_feedback?: string | null;
          admin_rating?: number | null;
          admin_feedback?: string | null;
          rejection_reason?: string | null;
          metadata?: Json;
          promoted_to_bank?: boolean;
          bank_question_id?: string | null;
          updated_at?: string;
          approved_at?: string | null;
        };
      };
      attachments: {
        Row: {
          id: string;
          question_id: string;
          file_name: string;
          file_type: string;
          file_size: number | null;
          mime_type: string | null;
          storage_path: string;
          storage_bucket: string;
          is_processed: boolean;
          ocr_text: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          question_id: string;
          file_name: string;
          file_type: string;
          file_size?: number | null;
          mime_type?: string | null;
          storage_path: string;
          storage_bucket?: string;
          is_processed?: boolean;
          ocr_text?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          question_id?: string;
          file_name?: string;
          file_type?: string;
          file_size?: number | null;
          mime_type?: string | null;
          storage_path?: string;
          storage_bucket?: string;
          is_processed?: boolean;
          ocr_text?: string | null;
          metadata?: Json;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: 'question_answered' | 'human_response_ready' | 'response_approved' | 'claim_assigned';
          title: string;
          message: string;
          question_id: string | null;
          response_id: string | null;
          human_response_id: string | null;
          link: string | null;
          is_read: boolean;
          read_at: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          type: 'question_answered' | 'human_response_ready' | 'response_approved' | 'claim_assigned';
          title: string;
          message: string;
          question_id?: string | null;
          response_id?: string | null;
          human_response_id?: string | null;
          link?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: 'question_answered' | 'human_response_ready' | 'response_approved' | 'claim_assigned';
          title?: string;
          message?: string;
          question_id?: string | null;
          response_id?: string | null;
          human_response_id?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          metadata?: Json;
        };
      };
      question_claims: {
        Row: {
          id: string;
          question_id: string;
          creator_id: string;
          status: string;
          claimed_at: string;
          started_at: string | null;
          completed_at: string | null;
          released_at: string | null;
          claim_notes: string | null;
          release_reason: string | null;
        };
        Insert: {
          id?: string;
          question_id: string;
          creator_id?: string;
          status?: string;
          claimed_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          released_at?: string | null;
          claim_notes?: string | null;
          release_reason?: string | null;
        };
        Update: {
          id?: string;
          question_id?: string;
          creator_id?: string;
          status?: string;
          started_at?: string | null;
          completed_at?: string | null;
          released_at?: string | null;
          claim_notes?: string | null;
          release_reason?: string | null;
        };
      };
      creator_profiles: {
        Row: {
          id: string;
          profile_id: string;
          total_responses: number;
          average_rating: number | null;
          total_claims: number;
          active_claims: number;
          is_available: boolean;
          max_active_claims: number;
          expertise: Json;
          is_active: boolean;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          total_responses?: number;
          average_rating?: number | null;
          total_claims?: number;
          active_claims?: number;
          is_available?: boolean;
          max_active_claims?: number;
          expertise?: Json;
          is_active?: boolean;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          total_responses?: number;
          average_rating?: number | null;
          total_claims?: number;
          active_claims?: number;
          is_available?: boolean;
          max_active_claims?: number;
          expertise?: Json;
          is_active?: boolean;
          approved_at?: string | null;
          updated_at?: string;
        };
      };
      saved_explanations: {
        Row: {
          id: string;
          user_id: string;
          question_id: string;
          ai_response_id: string | null;
          human_response_id: string | null;
          notes: string | null;
          tags: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          question_id: string;
          ai_response_id?: string | null;
          human_response_id?: string | null;
          notes?: string | null;
          tags?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          notes?: string | null;
          tags?: string[];
        };
      };
      milo_conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          title?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string | null;
          updated_at?: string;
        };
      };
      milo_messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: string;
          content: string;
          message_type: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role: string;
          content: string;
          message_type?: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          content?: string;
          message_type?: string;
          metadata?: Json;
        };
      };
      user_learning_profiles: {
        Row: {
          id: string;
          user_id: string;
          preferred_learning_style: string | null;
          response_time_preference: string | null;
          topic_mastery: Json;
          weakness_areas: Json;
          peak_study_hours: Json;
          average_session_length_minutes: number | null;
          total_study_sessions: number;
          common_mistake_types: Json;
          question_type_preferences: Json;
          total_questions_asked: number;
          total_ai_interactions: number;
          total_human_help_requests: number;
          average_rating_given: number | null;
          hint_frequency: string | null;
          explanation_depth: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          preferred_learning_style?: string | null;
          response_time_preference?: string | null;
          topic_mastery?: Json;
          weakness_areas?: Json;
          peak_study_hours?: Json;
          average_session_length_minutes?: number | null;
          total_study_sessions?: number;
          common_mistake_types?: Json;
          question_type_preferences?: Json;
          total_questions_asked?: number;
          total_ai_interactions?: number;
          total_human_help_requests?: number;
          average_rating_given?: number | null;
          hint_frequency?: string | null;
          explanation_depth?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          preferred_learning_style?: string | null;
          response_time_preference?: string | null;
          topic_mastery?: Json;
          weakness_areas?: Json;
          peak_study_hours?: Json;
          average_session_length_minutes?: number | null;
          total_study_sessions?: number;
          common_mistake_types?: Json;
          question_type_preferences?: Json;
          total_questions_asked?: number;
          total_ai_interactions?: number;
          total_human_help_requests?: number;
          average_rating_given?: number | null;
          hint_frequency?: string | null;
          explanation_depth?: string | null;
          updated_at?: string;
        };
      };
      user_progress: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          questions_asked: number;
          questions_answered_correctly: number;
          ai_interactions: number;
          study_time_minutes: number;
          topics_practiced: Json;
          practice_score: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          date?: string;
          questions_asked?: number;
          questions_answered_correctly?: number;
          ai_interactions?: number;
          study_time_minutes?: number;
          topics_practiced?: Json;
          practice_score?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          questions_asked?: number;
          questions_answered_correctly?: number;
          ai_interactions?: number;
          study_time_minutes?: number;
          topics_practiced?: Json;
          practice_score?: number;
        };
      };
      practice_questions: {
        Row: {
          id: string;
          subject: string;
          domain: string;
          topic_id: string;
          question_text: string;
          question_type: string;
          choices: Json;
          correct_answer: string;
          explanation: string;
          difficulty: string;
          source: string | null;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          subject: string;
          domain: string;
          topic_id: string;
          question_text: string;
          question_type?: string;
          choices?: Json;
          correct_answer: string;
          explanation: string;
          difficulty?: string;
          source?: string | null;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          subject?: string;
          domain?: string;
          topic_id?: string;
          question_text?: string;
          question_type?: string;
          choices?: Json;
          correct_answer?: string;
          explanation?: string;
          difficulty?: string;
          source?: string | null;
          display_order?: number;
        };
      };
      practice_attempts: {
        Row: {
          id: string;
          user_id: string;
          question_id: string;
          session_id: string | null;
          topic_id: string;
          subject: string;
          domain: string;
          selected_answer: string | null;
          is_correct: boolean;
          time_spent_seconds: number | null;
          attempted_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          question_id: string;
          session_id?: string | null;
          topic_id: string;
          subject: string;
          domain: string;
          selected_answer?: string | null;
          is_correct?: boolean;
          time_spent_seconds?: number | null;
          attempted_at?: string;
        };
        Update: {
          selected_answer?: string | null;
          is_correct?: boolean;
          time_spent_seconds?: number | null;
        };
      };
      practice_sessions: {
        Row: {
          id: string;
          user_id: string;
          session_type: string;
          mode_key: string | null;
          status: string;
          topic_id: string | null;
          section_filter: string | null;
          difficulty_filter: string | null;
          domain_filter: string | null;
          question_count_target: number | null;
          shuffle_questions: boolean | null;
          allow_backtracking: boolean | null;
          show_timer: boolean | null;
          adaptive: boolean | null;
          resume_allowed: boolean | null;
          session_seed: string | null;
          generated_question_ids: Json;
          last_question_index: number;
          challenge_state: Json;
          total_questions: number;
          correct_answers: number;
          score_percentage: number;
          time_limit_seconds: number | null;
          time_taken_seconds: number | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          session_type?: string;
          mode_key?: string | null;
          status?: string;
          topic_id?: string | null;
          section_filter?: string | null;
          difficulty_filter?: string | null;
          domain_filter?: string | null;
          question_count_target?: number | null;
          shuffle_questions?: boolean | null;
          allow_backtracking?: boolean | null;
          show_timer?: boolean | null;
          adaptive?: boolean | null;
          resume_allowed?: boolean | null;
          session_seed?: string | null;
          generated_question_ids?: Json;
          last_question_index?: number;
          challenge_state?: Json;
          total_questions?: number;
          correct_answers?: number;
          score_percentage?: number;
          time_limit_seconds?: number | null;
          time_taken_seconds?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          mode_key?: string | null;
          status?: string;
          generated_question_ids?: Json;
          last_question_index?: number;
          challenge_state?: Json;
          correct_answers?: number;
          total_questions?: number;
          score_percentage?: number;
          time_taken_seconds?: number | null;
          started_at?: string | null;
          completed_at?: string | null;
        };
      };
      creator_insights: {
        Row: {
          id: string;
          creator_id: string;
          user_id: string;
          issue_type: string | null;
          issue_description: string | null;
          learning_style_observation: string | null;
          recommended_approach: string | null;
          question_id: string | null;
          response_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          creator_id: string;
          user_id: string;
          issue_type?: string | null;
          issue_description?: string | null;
          learning_style_observation?: string | null;
          recommended_approach?: string | null;
          question_id?: string | null;
          response_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          issue_type?: string | null;
          issue_description?: string | null;
          learning_style_observation?: string | null;
          recommended_approach?: string | null;
        };
      };
      skills: {
        Row: {
          id: string;
          domain_id: string;
          name: string;
          slug: string;
          description: string | null;
          code: string | null;
          display_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          domain_id: string;
          name: string;
          slug: string;
          description?: string | null;
          code?: string | null;
          display_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          domain_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          code?: string | null;
          display_order?: number;
        };
      };
      import_batches: {
        Row: {
          id: string;
          user_id: string;
          status: 'pending' | 'processing' | 'ai_extraction' | 'manual_review' | 'completed' | 'failed';
          batch_name: string | null;
          source_description: string | null;
          total_files: number;
          processed_files: number;
          total_questions: number;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
          error_message: string | null;
          ai_extraction_enabled: boolean;
        };
        Insert: {
          id?: string;
          user_id?: string;
          status?: 'pending' | 'processing' | 'ai_extraction' | 'manual_review' | 'completed' | 'failed';
          batch_name?: string | null;
          source_description?: string | null;
          total_files?: number;
          processed_files?: number;
          total_questions?: number;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
          error_message?: string | null;
          ai_extraction_enabled?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          status?: 'pending' | 'processing' | 'ai_extraction' | 'manual_review' | 'completed' | 'failed';
          batch_name?: string | null;
          source_description?: string | null;
          total_files?: number;
          processed_files?: number;
          total_questions?: number;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
          error_message?: string | null;
          ai_extraction_enabled?: boolean;
        };
      };
      import_files: {
        Row: {
          id: string;
          batch_id: string;
          file_name: string;
          file_type: string;
          file_size: number | null;
          storage_path: string;
          status: 'pending' | 'processing' | 'ai_extraction' | 'manual_review' | 'completed' | 'failed';
          extracted_text: string | null;
          error_message: string | null;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          batch_id: string;
          file_name: string;
          file_type: string;
          file_size?: number | null;
          storage_path: string;
          status?: 'pending' | 'processing' | 'ai_extraction' | 'manual_review' | 'completed' | 'failed';
          extracted_text?: string | null;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          batch_id?: string;
          file_name?: string;
          file_type?: string;
          file_size?: number | null;
          storage_path?: string;
          status?: 'pending' | 'processing' | 'ai_extraction' | 'manual_review' | 'completed' | 'failed';
          extracted_text?: string | null;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
      };
      question_imports: {
        Row: {
          id: string;
          batch_id: string | null;
          file_id: string | null;
          user_id: string;
          status: 'pending' | 'extracted' | 'reviewing' | 'approved' | 'rejected' | 'published' | 'duplicate_detected';
          question_text: string;
          question_format: 'multiple_choice' | 'numeric_entry' | 'passage_based' | 'graph_table' | 'image_based' | 'two_part' | 'multi_select';
          choices: Json | null;
          correct_answer: string | null;
          explanation: string | null;
          hint: string | null;
          section: 'math' | 'reading' | 'writing' | null;
          domain_id: string | null;
          skill_id: string | null;
          difficulty: 'easy' | 'medium' | 'hard' | null;
          tags: string[];
          estimated_time_seconds: number | null;
          calculator_allowed: boolean;
          source: 'official' | 'creator' | 'community' | 'imported' | 'practice_test';
          source_reference: string | null;
          duplicate_of: string | null;
          similarity_score: number | null;
          section_confidence: number | null;
          domain_confidence: number | null;
          skill_confidence: number | null;
          difficulty_confidence: number | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          published_question_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          batch_id?: string | null;
          file_id?: string | null;
          user_id?: string;
          status?: 'pending' | 'extracted' | 'reviewing' | 'approved' | 'rejected' | 'published' | 'duplicate_detected';
          question_text: string;
          question_format?: 'multiple_choice' | 'numeric_entry' | 'passage_based' | 'graph_table' | 'image_based' | 'two_part' | 'multi_select';
          choices?: Json | null;
          correct_answer?: string | null;
          explanation?: string | null;
          hint?: string | null;
          section?: 'math' | 'reading' | 'writing' | null;
          domain_id?: string | null;
          skill_id?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard' | null;
          tags?: string[];
          estimated_time_seconds?: number | null;
          calculator_allowed?: boolean;
          source?: 'official' | 'creator' | 'community' | 'imported' | 'practice_test';
          source_reference?: string | null;
          duplicate_of?: string | null;
          similarity_score?: number | null;
          section_confidence?: number | null;
          domain_confidence?: number | null;
          skill_confidence?: number | null;
          difficulty_confidence?: number | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          published_question_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          batch_id?: string;
          file_id?: string | null;
          user_id?: string;
          status?: 'pending' | 'extracted' | 'reviewing' | 'approved' | 'rejected' | 'published' | 'duplicate_detected';
          question_text?: string;
          question_format?: 'multiple_choice' | 'numeric_entry' | 'passage_based' | 'graph_table' | 'image_based' | 'two_part' | 'multi_select';
          choices?: Json | null;
          correct_answer?: string | null;
          explanation?: string | null;
          hint?: string | null;
          section?: 'math' | 'reading' | 'writing' | null;
          domain_id?: string | null;
          skill_id?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard' | null;
          tags?: string[];
          estimated_time_seconds?: number | null;
          calculator_allowed?: boolean;
          source?: 'official' | 'creator' | 'community' | 'imported' | 'practice_test';
          source_reference?: string | null;
          duplicate_of?: string | null;
          similarity_score?: number | null;
          section_confidence?: number | null;
          domain_confidence?: number | null;
          skill_confidence?: number | null;
          difficulty_confidence?: number | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          review_notes?: string | null;
          published_question_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      question_bank: {
        Row: {
          id: string;
          display_id: string | null;
          question_text: string;
          question_text_html: string | null;
          passage: string | null;
          passage_html: string | null;
          passage_id: string | null;
          image_url: string | null;
          image_caption: string | null;
          graph_data: Json | null;
          question_format: 'multiple_choice' | 'numeric_entry' | 'passage_based' | 'graph_table' | 'image_based' | 'two_part' | 'multi_select';
          choices: Json;
          correct_answer: string;
          explanation: string | null;
          explanation_html: string | null;
          alternative_explanation: string | null;
          hint: string | null;
          section: 'math' | 'reading' | 'writing';
          domain_id: string | null;
          skill_id: string | null;
          difficulty: 'easy' | 'medium' | 'hard';
          tags: string[];
          gamemodes: string[] | null;
          visual_spec: Json | null;
          visual_data: Json | null;
          estimated_time_seconds: number;
          calculator_allowed: boolean;
          source: 'official' | 'creator' | 'community' | 'imported' | 'practice_test';
          source_reference: string | null;
          source_question_id: string | null;
          created_by: string | null;
          reviewed_by: string | null;
          published_by: string | null;
          status: 'draft' | 'pending_review' | 'approved' | 'published' | 'archived' | 'rejected';
          rejection_reason: string | null;
          times_used: number;
          times_correct: number;
          times_incorrect: number;
          average_time_seconds: number | null;
          admin_notes: string | null;
          flags: Json;
          created_at: string;
          updated_at: string;
          reviewed_at: string | null;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          display_id?: string | null;
          question_text: string;
          question_text_html?: string | null;
          passage?: string | null;
          passage_html?: string | null;
          passage_id?: string | null;
          image_url?: string | null;
          image_caption?: string | null;
          graph_data?: Json | null;
          question_format?: 'multiple_choice' | 'numeric_entry' | 'passage_based' | 'graph_table' | 'image_based' | 'two_part' | 'multi_select';
          choices?: Json;
          correct_answer: string;
          explanation?: string | null;
          explanation_html?: string | null;
          alternative_explanation?: string | null;
          hint?: string | null;
          section: 'math' | 'reading' | 'writing';
          domain_id?: string | null;
          skill_id?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard';
          tags?: string[];
          gamemodes?: string[] | null;
          visual_spec?: Json | null;
          visual_data?: Json | null;
          estimated_time_seconds?: number;
          calculator_allowed?: boolean;
          source?: 'official' | 'creator' | 'community' | 'imported' | 'practice_test';
          source_reference?: string | null;
          source_question_id?: string | null;
          created_by?: string | null;
          reviewed_by?: string | null;
          published_by?: string | null;
          status?: 'draft' | 'pending_review' | 'approved' | 'published' | 'archived' | 'rejected';
          rejection_reason?: string | null;
          times_used?: number;
          times_correct?: number;
          times_incorrect?: number;
          average_time_seconds?: number | null;
          admin_notes?: string | null;
          flags?: Json;
          created_at?: string;
          updated_at?: string;
          reviewed_at?: string | null;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          display_id?: string | null;
          question_text?: string;
          question_text_html?: string | null;
          passage?: string | null;
          passage_html?: string | null;
          passage_id?: string | null;
          image_url?: string | null;
          image_caption?: string | null;
          graph_data?: Json | null;
          question_format?: 'multiple_choice' | 'numeric_entry' | 'passage_based' | 'graph_table' | 'image_based' | 'two_part' | 'multi_select';
          choices?: Json;
          correct_answer?: string;
          explanation?: string | null;
          explanation_html?: string | null;
          alternative_explanation?: string | null;
          hint?: string | null;
          section?: 'math' | 'reading' | 'writing';
          domain_id?: string | null;
          skill_id?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard';
          tags?: string[];
          gamemodes?: string[] | null;
          visual_spec?: Json | null;
          visual_data?: Json | null;
          estimated_time_seconds?: number;
          calculator_allowed?: boolean;
          source?: 'official' | 'creator' | 'community' | 'imported' | 'practice_test';
          source_reference?: string | null;
          source_question_id?: string | null;
          created_by?: string | null;
          reviewed_by?: string | null;
          published_by?: string | null;
          status?: 'draft' | 'pending_review' | 'approved' | 'published' | 'archived' | 'rejected';
          rejection_reason?: string | null;
          times_used?: number;
          times_correct?: number;
          times_incorrect?: number;
          average_time_seconds?: number | null;
          admin_notes?: string | null;
          flags?: Json;
          updated_at?: string;
          reviewed_at?: string | null;
          published_at?: string | null;
        };
      };
      videos: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          tags: string[];
          video_url: string;
          video_storage_path: string | null;
          video_storage_bucket: string | null;
          thumbnail_url: string | null;
          subject: 'math' | 'reading' | 'writing' | null;
          topic: string | null;
          difficulty: 'easy' | 'medium' | 'hard' | null;
          question_type: string | null;
          creator_id: string;
          creator_name: string | null;
          views: number;
          source_question_id: string | null;
          status: 'published' | 'unlisted' | 'draft';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          tags?: string[];
          video_url: string;
          video_storage_path?: string | null;
          video_storage_bucket?: string | null;
          thumbnail_url?: string | null;
          subject?: 'math' | 'reading' | 'writing' | null;
          topic?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard' | null;
          question_type?: string | null;
          creator_id: string;
          creator_name?: string | null;
          views?: number;
          source_question_id?: string | null;
          status?: 'published' | 'unlisted' | 'draft';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          tags?: string[];
          video_url?: string;
          video_storage_path?: string | null;
          video_storage_bucket?: string | null;
          thumbnail_url?: string | null;
          subject?: 'math' | 'reading' | 'writing' | null;
          topic?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard' | null;
          question_type?: string | null;
          creator_name?: string | null;
          views?: number;
          status?: 'published' | 'unlisted' | 'draft';
          updated_at?: string;
        };
      };
      mascot_profiles: {
        Row: {
          id: string;
          user_id: string;
          credits: number;
          total_earned: number;
          streak_days: number;
          last_login_date: string | null;
          mascot_config: Json;
          owned_items: string[];
          equipped_items: Json;
          positions: Json;
          stats: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          credits?: number;
          total_earned?: number;
          streak_days?: number;
          last_login_date?: string | null;
          mascot_config?: Json;
          owned_items?: string[];
          equipped_items?: Json;
          positions?: Json;
          stats?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          credits?: number;
          total_earned?: number;
          streak_days?: number;
          last_login_date?: string | null;
          mascot_config?: Json;
          owned_items?: string[];
          equipped_items?: Json;
          positions?: Json;
          stats?: Json;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'student' | 'creator' | 'admin';
      question_status: 'draft' | 'pending' | 'processing' | 'ai_ready' | 'human_requested' | 'claimed' | 'human_ready' | 'completed' | 'archived';
      response_status: 'pending' | 'processing' | 'ready' | 'failed';
      notification_type: 'question_answered' | 'human_response_ready' | 'response_approved' | 'claim_assigned';
      subscription_tier: 'free' | 'pro' | 'premium';
      role_request_status: 'pending' | 'approved' | 'rejected' | 'cancelled';
      audit_action: 'role_changed' | 'role_request_approved' | 'role_request_rejected' | 'team_email_added' | 'team_email_removed' | 'user_suspended' | 'user_unsuspended' | 'question_claimed' | 'question_released' | 'response_approved' | 'response_rejected';
      question_format: 'multiple_choice' | 'numeric_entry' | 'passage_based' | 'graph_table' | 'image_based' | 'two_part' | 'multi_select';
      question_bank_status: 'draft' | 'pending_review' | 'approved' | 'published' | 'archived' | 'rejected';
      question_source: 'official' | 'creator' | 'community' | 'imported' | 'practice_test';
      sat_section: 'math' | 'reading' | 'writing';
      difficulty_level: 'easy' | 'medium' | 'hard';
      import_batch_status: 'pending' | 'processing' | 'ai_extraction' | 'manual_review' | 'completed' | 'failed';
      question_import_status: 'pending' | 'extracted' | 'reviewing' | 'approved' | 'rejected' | 'published' | 'duplicate_detected';
    };
  };
};
